# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'BubbleTransition' do
  pod 'BubbleTransition', path: '../'
end

target 'BubbleTransitionTests' do

end

use_frameworks!

